name: Vercel Storybook Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on: [pull_request]
jobs:
  Deploy-PR-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Move Vercel JSON file
        run: |
          rm vercel.json
          rm pnpm-lock.yaml
          mv vercel-storybook.json vercel.json
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Branch name
        run: echo Branch was set to ${{ steps.extract_branch.outputs.branch }}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: vercel deploy -m githubCommitRef=${{ steps.extract_branch.outputs.branch }} -m githubDeployment="1" -m githubCommitRepo=${{ github.repository }} --token=${{ secrets.VERCEL_TOKEN }} >> vcurl.txt
      - name: Read Vercel Deployment URL
        id: readfile
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: vcurl.txt
      - name: Run find-and-replace to remove slashes in branch names
        uses: mad9000/actions-find-and-replace-string@3
        id: findandreplace
        with:
          source: ${{ steps.extract_branch.outputs.branch }}
          find: '/'
          replace: '-'
      - name: Truncate to the max length
        uses: bhowell2/github-substring-action@1.0.2
        id: truncation
        with:
          value: ${{ steps.findandreplace.outputs.value }}
          length_from_start: 34
      # Check for trailing dash and remove it if present
      - name: Remove trailing dash
        id: remove_trailing_dash
        run: |
          TRUNCATED_BRANCH_NAME="${{ steps.truncation.outputs.substring }}"
          if [[ $TRUNCATED_BRANCH_NAME == *- ]]; then
            TRUNCATED_BRANCH_NAME="${TRUNCATED_BRANCH_NAME%?}"
          fi
          echo "TRUNCATED_BRANCH_NAME=$TRUNCATED_BRANCH_NAME" >> $GITHUB_ENV
          echo "TRUNCATED_BRANCH_NAME=${TRUNCATED_BRANCH_NAME}" >> $GITHUB_OUTPUT
      - name: Set Alias URL
        run: echo "ALIAS_URL=$(echo storybook-git-${{ steps.truncation.outputs.substring }}-vercel-support.vercel.app)" >> $GITHUB_ENV
      - name: Update aliasurl.txt
        run: echo Preview URL - https://${ALIAS_URL} >> aliasurl.txt
      - name: Aliasing the URL
        run: vercel alias set ${{ steps.readfile.outputs.content }} ${ALIAS_URL} --token=${{ secrets.VERCEL_TOKEN }} --scope=vercel-support
      - name: Comment the URL on the PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: output_url
          filePath: aliasurl.txt
